/**
 * Data access layer.
 * Tries the live API (Neon-backed, available when deployed with serverless functions),
 * then falls back to the static snapshot generated by scripts/ingest.mjs.
 */
const STATIC_URL = `${import.meta.env.BASE_URL}data/artdata.json`;

export async function loadData() {
  try {
    const res = await fetch('/api/data', { signal: AbortSignal.timeout(4000) });
    if (res.ok) {
      const json = await res.json();
      if (json?.periods?.length) return json;
    }
  } catch {
    /* API not available on this host — use the static snapshot */
  }
  const res = await fetch(STATIC_URL);
  if (!res.ok) throw new Error(`Failed to load art data (${res.status})`);
  return res.json();
}
